### ISSUE TITLE
link2005 and 2001, link 1120

### ISSUE THREAD

**Issue by fozi322** [ritz-1337/fortnite-external-evo.gj#8]
link2005: Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK2005	"bool bCornerBox" (?bCornerBox@@3_NA) already defined in aimbot.obj	evo.gj	E:\downloads\fort\evo.gj\sdk.obj	1		

link 2001: Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK2001	unresolved external symbol "void __cdecl aimbot(void)" (?aimbot@@YAXXZ)	evo.gj	E:\downloads\fort\evo.gj\render.obj	1		

link 1120: Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK1120	1 unresolved externals	evo.gj	E:\downloads\fort\x64\Release\evo.gj.exe	1		

![Screenshot 2024-03-31 175121](https://github.com/ritz-1337/fortnite-external-evo.gj/assets/148363151/d3831878-b860-406a-8eb2-0fb283916c49)

**Comment by mtralkhaldi2020** [comment]
THX I fix it

**Comment by mtralkhaldi2020** [comment]
THX I fix it

**Comment by fozi322** [comment]
THX I fix it
